language: python

python:
  - "3.6"

cache: pip

services:
  - postgresql
  - redis-server

before_install:
  - pip install pipenv
  - psql -c "CREATE DATABASE \"pulsar-testing\";" -U postgres

install:
  - pipenv install --dev
  - sed -i "s/postgresql:\/\//postgresql:\/\/postgres@/" instance/test_config.py

script:
  - make tests

after_success:
  - coveralls
