language: python

python:
  - "3.6"

cache: pip

services:
  - postgresql
  - redis-server

before_install:
   psql -c "CREATE DATABASE pulsar-testing;" -U postgres

install:
  - pip install -r requirements.txt
  - sed -i "s/postgresql:\/\//postgresql:\/\/postgres:/" instance/test_config.py

script:
  - pytest
